# Generated by Django 5.2.7 on 2025-11-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='inventory_name',
            field=models.CharField(default='default', max_length=128),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='category',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='lote',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_name',
            field=models.CharField(default='default', max_length=128),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='document_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='document_type',
            field=models.CharField(blank=True, choices=[('EA', 'Entrada'), ('SA', 'Salida')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='importbatch',
            unique_together={('checksum', 'inventory_name')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryrecord',
            unique_together={('document_type', 'document_number', 'product', 'batch')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('code', 'inventory_name')},
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['product', 'date'], name='inventory_i_product_2f833d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['warehouse', 'date'], name='inventory_i_warehou_7662fa_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['document_type', 'document_number'], name='inventory_i_documen_da83cf_idx'),
        ),
    ]
