# Generated by Django 5.2.7 on 2025-11-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_importbatch_checksum_importbatch_inventory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='initial_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
