# Generated by Django 5.2.7 on 2025-11-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_initial_balance_product_initial_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='document_type',
            field=models.CharField(blank=True, choices=[('1', 'AGROQUIMICOS-FERTILIZANTES Y ABONOS'), ('2', 'DOTACION Y SEGURIDAD'), ('3', 'MANTENIMIENTO'), ('4', 'MATERIAL DE EMPAQUE'), ('5', 'PAPELERIA Y ASEO')], max_length=4, null=True),
        ),
    ]
