# Generated by Django 5.2.8 on 2025-11-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryrecord_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrecord',
            name='final_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
    ]
