# Generated by Django 5.2.8 on 2025-11-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryrecord_final_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrecord',
            name='cost_center',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='document_type',
            field=models.CharField(blank=True, choices=[('EA', 'Entrada'), ('SA', 'Salida'), ('GF', 'Entrada')], max_length=4, null=True),
        ),
    ]
