# Generated by Django 5.2.8 on 2025-11-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryrecord_cost_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='cost_center',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
