# Generated by Django 5.2.8 on 2025-11-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventoryrecord_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='cost_center',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
